engines:
  eslint:
    enabled: true
  csslint:
    enabled: true
  nodesecurity:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - javascript
ratings:
  paths:
  - "app/**/*"
  - "config/**"
  - "**.js"
exclude_paths:
- public/**/*
- node_modules/**/*
